apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  template:
    spec:
      containers:
        - name: weather-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: LOG_LEVEL  
              value: Debug
          envFrom:
            - configMapRef:
                name: dev-weather-api-env-config
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
