apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: weather-api-dev

namespace: dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      environment: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: weather-api

images:
  - name: ghcr.io/aurbor/dotnet-sample-app
    newTag: dev

configMapGenerator:
  - name: weather-api-env-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=Debug

replicas:
  - name: weather-api
    count: 1
