apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  template:
    spec:
      containers:
        - name: weather-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: LOG_LEVEL
              value: Information
          envFrom:
            - configMapRef:
                name: prod-weather-api-env-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
