apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-api-dev-hybrid
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aurbor/k8s-argo-cd-poc.git
    targetRevision: main
    path: charts/weather-api/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
